name: CI
on:
    pull_request:
        paths-ignore:
            - docs/**
            - example/**
        branches: [main]
jobs:
    get_changed_packages:
        name: Get changed packages
        runs-on: ubuntu-latest
        outputs:
            names: ${{ steps.changed_packages.outputs.names }}
        steps:
            - uses: actions/checkout@v2
            - name: Find changed workspaces
              id: changed_packages
              uses: AlexShukel/get-changed-workspaces-action@main
            - run: echo "${{ steps.changed_packages.outputs.names }}"

    build:
        needs: [get_changed_packages]
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['14.x', '16.x']
                os: [ubuntu-latest]
                package: ${{ fromJson(needs.get_changed_packages.outputs.names) }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install global dependencies
              run: npm install

            - name: Build, lint and test in ${{ matrix.package }}
              run: npx turbo run build test lint --scope=${{ matrix.package }} --include-dependencies --no-deps
