name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['16.x', '18.x']
                os: [ubuntu-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install pnpm 8.6.7
              uses: pnpm/action-setup@v4
              with:
                  version: 8.6.7

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Build
              run: pnpm build

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test:ci
