name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['14.x', '16.x']
                os: [ubuntu-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install latest npm
              run: npm i -g npm@latest

            - name: Install global dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test
