name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    generate_matrix:
        name: Get changed packages
        runs-on: ubuntu-latest
        outputs:
            names: ${{ steps.changed_packages.outputs.names }}
            paths: ${{ steps.changed_packages.outputs.paths }}
            empty: ${{ steps.changed_packages.outputs.empty }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Find changed workspaces
              id: changed_packages
              uses: AlexShukel/get-changed-workspaces-action@v1.0.0
            - run: echo "${{ steps.changed_packages.outputs.names }}"

    build:
        needs: [generate_matrix]
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['14.x', '16.x']
                os: [ubuntu-latest]
                name: ${{ fromJson(needs.generate_matrix.outputs.names) }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install latest npm
              run: npm i -g npm@latest

            - name: Install global dependencies
              run: npm install

            - name: Build, lint and test in ${{ matrix.name }}
              run: npx turbo run build test lint --scope=${{ matrix.name }} --include-dependencies --no-deps
